# Generated by Django 3.1.7 on 2021-02-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(upload_to='galleries')),
                ('blog_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog')),
            ],
        ),
    ]
