# Generated by Django 3.1.6 on 2021-02-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
