# Generated by Django 3.1.6 on 2021-02-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
