# Generated by Django 3.1.6 on 2021-02-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Ask',
        ),
    ]
