# Generated by Django 3.1.6 on 2021-02-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210219_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='title',
            new_name='name',
        ),
    ]
