# Generated by Django 3.1.6 on 2021-02-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210219_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ask',
        ),
    ]
