# Generated by Django 3.1.6 on 2021-02-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_ask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('pdf', models.CharField(max_length=100)),
            ],
        ),
    ]
