# Generated by Django 3.1.6 on 2021-02-20 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210219_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
