# Generated by Django 3.1.5 on 2021-01-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='albums',
            new_name='album',
        ),
    ]
