# Generated by Django 3.1.4 on 2020-12-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20201230_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='availavle_authors',
            field=models.CharField(blank=True, choices=[('ERNEST', 'HEMINGWAY'), ('JOAN', 'DIDION'), ('RAY', 'BRADBURY'), ('AYN', 'RAND'), ('GILLIAN', 'FLYNN'), ('JANE', 'AUSTEN')], default='ERNEST', max_length=200),
        ),
    ]
