# Generated by Django 3.1.4 on 2020-12-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_author_availavle_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='availavle_authors',
            new_name='available_authors',
        ),
    ]
