# Generated by Django 3.1.4 on 2020-12-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_auto_20201231_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='available_authors',
            field=models.CharField(blank=True, choices=[('ERNEST HEMINGWAY', 'ERNEST HEMINGWAY'), ('JOAN DIDION', 'JOAN DIDION'), ('RAY BRADBURY', 'RAY BRADBURY'), ('AYN RAND', 'AYN RAND'), ('GILLIAN FLYNN', 'GILLIAN FLYNN'), ('JANE AUSTEN', 'JANE AUSTEN')], max_length=200),
        ),
    ]
