# Generated by Django 3.1.4 on 2020-12-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0012_auto_20201231_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='available_authors',
            field=models.CharField(blank=True, choices=[('Ernest Hemingway', 'Ernest Hemingway'), ('Joan Didion', 'Joan Didion'), ('Ray Bradbury', 'Ray Bradbury'), ('Ayn Rand', 'Ayn Rand'), ('Gillian Flynn', 'Gillian Flynn'), ('Jane Austen', 'Jane Austen')], max_length=200, unique=True),
        ),
    ]
