# Generated by Django 3.1.4 on 2020-12-31 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_app', '0014_landbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='book_app.author'),
        ),
        migrations.AlterField(
            model_name='landbook',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='book_app.book'),
        ),
        migrations.AlterField(
            model_name='landbook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
