# Generated by Django 3.1.4 on 2021-01-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0019_auto_20201231_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landbook',
            name='status',
            field=models.CharField(blank=True, choices=[('out', 'Book is out'), ('in', 'Book is in')], default='out', max_length=200),
        ),
    ]
