# Generated by Django 3.1.3 on 2020-11-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
