# Generated by Django 3.1.4 on 2021-01-27 22:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('imageloader', '0003_auto_20210122_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to='galleries/'),
        ),
    ]
