# Generated by Django 3.1.4 on 2021-01-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageloader', '0004_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
    ]
