# Generated by Django 3.1.4 on 2021-01-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0002_auto_20210120_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
