# Generated by Django 3.1.4 on 2021-01-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0008_post_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
    ]
