# Generated by Django 3.1.5 on 2021-02-07 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('publish_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='libraryapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BookCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 2, 14, 0, 43, 54, 41442, tzinfo=utc), help_text='default due date 7 days')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='libraryapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='libraryapp.user')),
            ],
        ),
    ]
