# Generated by Django 3.1.5 on 2021-01-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_auto_20210125_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/img/no_image.jpg', upload_to='products/%Y/%m/%d'),
        ),
    ]
