# Generated by Django 3.1.5 on 2021-02-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_auto_20210129_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/img/no_image.jpg', upload_to='products/%Y/%m/%d'),
        ),
    ]
