# Generated by Django 3.1.6 on 2021-02-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0009_auto_20210202_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
