# Generated by Django 3.0 on 2021-02-17 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='restroom',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED')], default=1, verbose_name='Status'),
        ),
    ]
