# Generated by Django 3.1.6 on 2021-04-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ushort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=200)),
                ('shortened_url', models.CharField(max_length=10)),
            ],
        ),
    ]
