# Generated by Django 3.1.7 on 2021-03-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_Shortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_url', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=20)),
                ('output_url', models.CharField(max_length=200)),
            ],
        ),
    ]
