# Generated by Django 3.1.7 on 2021-03-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url_shortener',
            old_name='input_url',
            new_name='url',
        ),
    ]
