# Generated by Django 3.1.6 on 2021-02-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rover_app', '0002_auto_20210205_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='camera_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='rover_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
