# Generated by Django 3.1.6 on 2021-02-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rover_app', '0003_auto_20210209_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
