# Generated by Django 3.1.6 on 2021-02-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rover_app', '0004_mediamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
