# Generated by Django 3.1.6 on 2021-02-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoundSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='for URL; no spaces')),
                ('address', models.CharField(max_length=100)),
                ('rocks', models.TextField()),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
