# Generated by Django 3.1.6 on 2021-02-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='short_url',
            new_name='short_urls',
        ),
    ]
