# Generated by Django 3.1.6 on 2021-02-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0002_remove_crystal_color'),
    ]

    operations = [
    ]
