# Generated by Django 3.1.6 on 2021-02-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crystal',
            name='color',
        ),
    ]
