# Generated by Django 3.1.6 on 2021-02-12 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compendium', '0005_auto_20210205_0454'),
        ('blog', '0002_auto_20210202_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='crystals',
            field=models.ManyToManyField(blank=True, help_text='hold CTRL to select more than 1 crystal', related_name='blog_posts', to='compendium.Crystal'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='use lowercase, alpha-numeric characters and replace all spaces with underscores', max_length=63, unique_for_month='pub_date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='hold CTRL to select more than 1 tag', related_name='blog_posts', to='compendium.Tag'),
        ),
    ]
