# Generated by Django 2.2.17 on 2021-01-27 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hedger_app', '0004_auto_20210126_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
