# Generated by Django 2.2.17 on 2021-02-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedger_app', '0008_balances_pax_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='balances',
            name='Account_value',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AddField(
            model_name='balances',
            name='PAX_value',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
