# Generated by Django 2.2.17 on 2021-02-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedger_app', '0010_auto_20210204_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balances',
            name='date_time',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
