# Generated by Django 2.2.17 on 2021-02-06 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hedger_app', '0011_auto_20210204_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balances',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
