# Generated by Django 2.2.17 on 2021-02-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedger_app', '0013_auto_20210206_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='balances',
            name='API_reply',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
