# Generated by Django 2.2.17 on 2021-02-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedger_app', '0015_auto_20210217_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balances',
            name='API_reply',
            field=models.CharField(default='hold', max_length=150),
        ),
        migrations.AlterField(
            model_name='balances',
            name='date_time',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
